### ISSUE TITLE
Suffering from NIH syndrome?

### ISSUE THREAD

**Issue by emansom** [iamdroppy/localghost#1]
Or is project exposure a serious issue in the IT industry?

Anyway, take a look at [mkcert](https://github.com/FiloSottile/mkcert) for local development and [step-ca ](https://github.com/smallstep/certificates) for a company-wide/internal CA.

**Comment by deehmabel** [comment]
suffering from bored syndrome

**Comment by iamdroppy** [comment]
suffering from boring syndrome.

**Comment by iamdroppy** [comment]
I have updated my comment. Please follow up if you have a concern.
